name: Postman CI - Users Delete

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    # Step 1: Check version Newman and Node
    - name: Check version Newman and Node
      run: |
        newman --version
        node --version
        
    # Step 2: Install Newman-Reporter-HtmlExtra
    - name: Install Newman-Reporter-HtmlExtra
      run: |
        sudo npm install -g newman-reporter-htmlextra

    # Step 3: Execute collection
    - name: Execute collection
      run: |
        newman run ./users-excluir-ci.json -e ./testes-env.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./docs/index.html

    # Step 4: Upload Test Report
    - name: Upload Test Report
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: ./docs/index.html
